apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-api-gateway
  labels:
    app: aegis
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-notification-worker
  labels:
    app: aegis
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-client
  labels:
    app: aegis
