apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-workload-identity
  namespace: aegis-prod
  annotations:
    azure.workload.identity/client-id: "__MANAGED_IDENTITY_CLIENT_ID__"
  labels:
    azure.workload.identity/use: "true"
    app.kubernetes.io/name: aegis-health
